### PR TITLE
added translations/cn

### PR DESCRIPTION
**Pull request by qbig**
Hey. Would this format work?

### CODE REVIEW

**Comment by qbig** [comment]
@paul-schaaf

**Comment by paul-schaaf** [comment]
for now we think the best way to do this is to just have a separate repo for the chinese translation. We've created it here https://github.com/project-serum/anchor-book-cn and you can make a new PR there.

You can just start a new `mdbook` project there. We will add the CNAME record and the `.github` folder once we have that set up on our side.

The translation repo should also indicate which commit of the english anchor book it's up to date with. This can be at the very beginning of the book and in the README.md.

**Comment by qbig** [comment]
@paul-schaaf it seems empty repo cannot be forked. I will just wait for you to add the CNAME record first?

**Comment by paul-schaaf** [comment]
I added sth to the repo. Does it work now?

**Pull request closed without merging**
